"use client";

import React from 'react';
import { useContractStore } from '@/store/useContractStore';

export function LivePreviewPanel() {
  const { contract, isYamlValid } = useContractStore();

  const rulesCount = contract.rules.length;
  const estimatedCost = (rulesCount * 0.005).toFixed(3);
  const affectedTables = 1 + (contract.dataset.table ? 1 : 0); // Mock dependency graph logic

  return (
    <div className="h-full flex flex-col bg-card border-t border-border">
      <div className="flex items-center justify-between px-4 py-2 border-b border-border bg-muted/30">
        <h4 className="text-sm font-bold text-foreground">Live Simulation & Plan</h4>
        {!isYamlValid && (
          <span className="text-xs text-red-500 font-semibold px-2 py-0.5 bg-red-500/10 rounded">
            Syntax Error - Fix YAML
          </span>
        )}
      </div>
      
      <div className="flex-1 p-4 grid grid-cols-4 gap-6 overflow-y-auto custom-scrollbar">
        {/* SQL Generation Preview */}
        <div className="col-span-2 space-y-2">
          <h5 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Generated SQL (Preview)</h5>
          <div className="bg-[#1e1e1e] border border-border rounded-lg p-3 h-32 overflow-y-auto">
            {contract.rules.length === 0 ? (
              <span className="text-muted-foreground text-sm italic">Add rules to generate SQL...</span>
            ) : (
              <pre className="text-green-400 font-mono text-xs whitespace-pre-wrap">
                {contract.rules.map((r, i) => {
                  if (r.type === 'not_null') return `-- Rule ${i+1}: Not Null\nSELECT COUNT(*) FROM ${contract.dataset.table || '{{table}}'} WHERE ${r.column || '{{column}}'} IS NULL;\n`;
                  if (r.type === 'custom_sql') return `-- Rule ${i+1}: Custom\n${r.sql}\n`;
                  return `-- Rule ${i+1}: ${r.type}\n-- (Auto-generated by engine)\n`;
                }).join('\n')}
              </pre>
            )}
          </div>
        </div>

        {/* Impact Analysis */}
        <div className="col-span-1 space-y-4">
          <div>
            <h5 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Impact Analysis</h5>
            <div className="space-y-3">
              <div className="flex justify-between items-center text-sm">
                <span className="text-foreground">Affected Tables</span>
                <span className="font-mono text-blue-400 font-bold">{affectedTables}</span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-foreground">Downstream Dashboards</span>
                <span className="font-mono text-yellow-400 font-bold">3</span>
              </div>
            </div>
          </div>
        </div>

        {/* Cost & Run Estimation */}
        <div className="col-span-1 space-y-4">
          <div>
            <h5 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-2">Execution Profile</h5>
            <div className="space-y-3">
              <div className="flex justify-between items-center text-sm">
                <span className="text-foreground">Estimated Runtime</span>
                <span className="font-mono font-bold text-foreground">{(rulesCount * 1.5).toFixed(1)}s</span>
              </div>
              <div className="flex justify-between items-center text-sm">
                <span className="text-foreground">Warehouse Cost</span>
                <span className="font-mono text-green-400 font-bold">${estimatedCost}/run</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
